# Generated by Django 4.2.27 on 2025-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaEPI",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registro_ca", models.CharField(db_index=True, max_length=50)),
                ("data_validade", models.DateField(blank=True, db_index=True, null=True)),
                ("situacao", models.CharField(blank=True, max_length=60)),
                ("nr_processo", models.CharField(blank=True, max_length=60)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("razao_social", models.CharField(blank=True, max_length=255)),
                ("natureza", models.CharField(blank=True, max_length=120)),
                ("nome_equipamento", models.CharField(blank=True, max_length=255)),
                ("descricao_equipamento", models.TextField(blank=True)),
                ("marca_ca", models.CharField(blank=True, max_length=120)),
                ("referencia", models.CharField(blank=True, max_length=120)),
                ("cor", models.CharField(blank=True, max_length=60)),
                ("aprovado_para_laudo", models.CharField(blank=True, max_length=60)),
                ("restricao_laudo", models.TextField(blank=True)),
                ("observacao_analise_laudo", models.TextField(blank=True)),
                ("cnpj_laboratorio", models.CharField(blank=True, max_length=20)),
                ("razao_social_laboratorio", models.CharField(blank=True, max_length=255)),
                ("nr_laudo", models.CharField(blank=True, max_length=60)),
                ("norma", models.CharField(blank=True, max_length=120)),
                ("ultima_atualizacao", models.DateTimeField()),
            ],
            options={
                "ordering": ["-data_validade", "registro_ca"],
            },
        ),
    ]
