# Generated by Django 4.2.27 on 2025-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caepi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caepi",
            name="aprovado_para_laudo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caepi",
            name="cor",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caepi",
            name="nr_laudo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caepi",
            name="nr_processo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caepi",
            name="situacao",
            field=models.TextField(blank=True),
        ),
    ]
