# Generated by Django 4.2.27 on 2025-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caepi", "0002_alter_caepi_unlimited_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caepi",
            name="marca_ca",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caepi",
            name="natureza",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caepi",
            name="norma",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="caepi",
            name="referencia",
            field=models.TextField(blank=True),
        ),
    ]
