# Generated by Django 4.2.27 on 2026-01-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("funcionarios", "0025_alter_funcionario_validacao_recebimento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcidenteTrabalho",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_ocorrencia",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("descricao_ocorrido", models.TextField(blank=True)),
                (
                    "tipo_local",
                    models.CharField(
                        choices=[
                            ("", "Selecione"),
                            ("estabelecimento_brasil", "Estabelecimento do empregador no Brasil"),
                            ("estabelecimento_exterior", "Estabelecimento do empregador no Exterior"),
                            ("estabelecimento_terceiros", "Estabelecimento de terceiros"),
                            ("via_publica", "Via publica"),
                            ("area_rural", "Area rural"),
                            ("embarcacao", "Embarcacao"),
                            ("outros", "Outros"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ambiente", models.CharField(max_length=120)),
                ("descricao_local", models.CharField(max_length=80)),
                ("cep", models.CharField(max_length=9)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("", "Selecione"),
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapa"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceara"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espirito Santo"),
                            ("GO", "Goias"),
                            ("MA", "Maranhao"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Para"),
                            ("PB", "Paraiba"),
                            ("PR", "Parana"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piaui"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondonia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "Sao Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cidade", models.CharField(max_length=120)),
                (
                    "tipo_logradouro",
                    models.CharField(
                        choices=[
                            ("", "Selecione"),
                            ("rua", "Rua"),
                            ("avenida", "Avenida"),
                            ("estrada", "Estrada"),
                            ("praca", "Praca"),
                            ("area", "Area"),
                            ("acesso", "Acesso"),
                            ("alameda", "Alameda"),
                            ("bairro", "Bairro"),
                            ("beco", "Beco"),
                            ("boulevard", "Boulevard"),
                            ("caminho", "Caminho"),
                            ("chacara", "Chacara"),
                            ("conjunto", "Conjunto"),
                            ("condominio", "Condominio"),
                            ("distrito", "Distrito"),
                            ("fazenda", "Fazenda"),
                            ("jardim", "Jardim"),
                            ("loteamento", "Loteamento"),
                            ("parque", "Parque"),
                            ("rodovia", "Rodovia"),
                            ("rua_particular", "Rua Particular"),
                            ("servidao", "Servidao"),
                            ("sitio", "Sitio"),
                            ("travessa", "Travessa"),
                            ("via", "Via"),
                            ("vila", "Vila"),
                            ("outros", "Outros"),
                        ],
                        max_length=40,
                    ),
                ),
                ("endereco", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(max_length=90)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acidentes_trabalho",
                        to="funcionarios.funcionario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_ocorrencia"],
            },
        ),
    ]

