# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acidentetrabalho",
            name="tipo_registro",
            field=models.CharField(
                choices=[("acidente", "Acidente"), ("quase_acidente", "Quase acidente")],
                default="acidente",
                max_length=20,
            ),
        ),
    ]

