# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0002_acidentetrabalho_tipo_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="acidentetrabalho",
            name="tipo_acidente",
            field=models.CharField(
                choices=[
                    ("tipico", "Tipico"),
                    ("doenca", "Doenca"),
                    ("trajeto", "Trajeto"),
                    ("outros", "Outros tipos"),
                ],
                default="tipico",
                max_length=20,
            ),
        ),
    ]

