# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0003_acidentetrabalho_tipo_acidente"),
    ]

    operations = [
        migrations.AddField(
            model_name="acidentetrabalho",
            name="trajeto_evento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("atropelamento", "Atropelamento"),
                    ("colisao", "Colisao"),
                    ("outros", "Outros"),
                ],
                max_length=20,
            ),
        ),
    ]

