# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0004_acidentetrabalho_trajeto_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="acidentetrabalho",
            name="ultimo_dia_trabalhado",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="horas_trabalhadas",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="houve_afastamento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="houve_obito",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="data_obito",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="houve_comunicacao_policia",
            field=models.BooleanField(default=False),
        ),
    ]

