# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0005_campos_investigacao_basicos"),
    ]

    operations = [
        migrations.AddField(
            model_name="acidentetrabalho",
            name="situacao_geradora",
            field=models.CharField(
                choices=[
                    ("", "Selecione"),
                    ("Impacto de pessoa contra objeto parado", "Impacto de pessoa contra objeto parado"),
                    ("Impacto de pessoa contra objeto em movimento", "Impacto de pessoa contra objeto em movimento"),
                    ("Impacto sofrido por pessoa de objeto que cai", "Impacto sofrido por pessoa de objeto que cai"),
                    ("Impacto sofrido por pessoa de objeto projetado", "Impacto sofrido por pessoa de objeto projetado"),
                    ("Impacto sofrido por pessoa, NIC", "Impacto sofrido por pessoa, NIC"),
                    (
                        "Queda de pessoa com diferença de nível de andaime, passagem, plataforma, etc.",
                        "Queda de pessoa com diferença de nível de andaime, passagem, plataforma, etc.",
                    ),
                    (
                        "Queda de pessoa com diferença de nível de escada móvel ou fixada",
                        "Queda de pessoa com diferença de nível de escada móvel ou fixada",
                    ),
                    (
                        "Queda de pessoa com diferença de nível de material empilhado",
                        "Queda de pessoa com diferença de nível de material empilhado",
                    ),
                    (
                        "Queda de pessoa com diferença de nível de veículo",
                        "Queda de pessoa com diferença de nível de veículo",
                    ),
                    (
                        "Queda de pessoa com diferença de nível em escada permanente",
                        "Queda de pessoa com diferença de nível em escada permanente",
                    ),
                    (
                        "Queda de pessoa com diferença de nível em poço, escavação, abertura no piso, etc.",
                        "Queda de pessoa com diferença de nível em poço, escavação, abertura no piso, etc.",
                    ),
                    ("Queda de pessoa com diferença de nível, NIC", "Queda de pessoa com diferença de nível, NIC"),
                    (
                        "Queda de pessoa em mesmo nível em passagem ou superfície de sustentação",
                        "Queda de pessoa em mesmo nível em passagem ou superfície de sustentação",
                    ),
                    (
                        "Queda de pessoa em mesmo nível sobre ou contra alguma coisa",
                        "Queda de pessoa em mesmo nível sobre ou contra alguma coisa",
                    ),
                    ("Queda de pessoa em mesmo nível, NIC", "Queda de pessoa em mesmo nível, NIC"),
                    (
                        "Aprisionamento em, sob ou entre objetos em movimento convergente",
                        "Aprisionamento em, sob ou entre objetos em movimento convergente",
                    ),
                    (
                        "Aprisionamento em, sob ou entre objeto parado e outro em movimento",
                        "Aprisionamento em, sob ou entre objeto parado e outro em movimento",
                    ),
                    (
                        "Aprisionamento em, sob ou entre dois ou mais objetos em movimento",
                        "Aprisionamento em, sob ou entre dois ou mais objetos em movimento",
                    ),
                    (
                        "Aprisionamento em, sob ou entre desabamento ou desmoronamento",
                        "Aprisionamento em, sob ou entre desabamento ou desmoronamento",
                    ),
                    ("Aprisionamento em, sob ou entre, NIC", "Aprisionamento em, sob ou entre, NIC"),
                    (
                        "Atrito ou abrasão por encostar, pisar, ajoelhar ou sentar em objeto",
                        "Atrito ou abrasão por encostar, pisar, ajoelhar ou sentar em objeto",
                    ),
                    ("Atrito ou abrasão por manusear objeto", "Atrito ou abrasão por manusear objeto"),
                    ("Atrito ou abrasão por objeto em vibração", "Atrito ou abrasão por objeto em vibração"),
                    ("Atrito ou abrasão por corpo estranho no olho", "Atrito ou abrasão por corpo estranho no olho"),
                    ("Atrito ou abrasão por compressão repetitiva", "Atrito ou abrasão por compressão repetitiva"),
                    ("Atrito ou abrasão, NIC", "Atrito ou abrasão, NIC"),
                    ("Reação do corpo a movimento involuntário", "Reação do corpo a movimento involuntário"),
                    ("Reação do corpo a movimento voluntário", "Reação do corpo a movimento voluntário"),
                    ("Esforço excessivo ao erguer objeto", "Esforço excessivo ao erguer objeto"),
                    ("Esforço excessivo ao empurrar ou puxar objeto", "Esforço excessivo ao empurrar ou puxar objeto"),
                    (
                        "Esforço excessivo ao manejar, sacudir ou arremessar objeto",
                        "Esforço excessivo ao manejar, sacudir ou arremessar objeto",
                    ),
                    ("Esforço excessivo, NIC", "Esforço excessivo, NIC"),
                    ("Elétrica, exposição à energia", "Elétrica, exposição à energia"),
                    (
                        "Temperatura muito alta, contato com objeto ou substância a",
                        "Temperatura muito alta, contato com objeto ou substância a",
                    ),
                    (
                        "Temperatura muito baixa, contato com objeto ou substância a",
                        "Temperatura muito baixa, contato com objeto ou substância a",
                    ),
                    ("Temperatura ambiente elevada, exposição à", "Temperatura ambiente elevada, exposição à"),
                    ("Temperatura ambiente baixa, exposição à", "Temperatura ambiente baixa, exposição à"),
                    (
                        "Inalação de substância cáustica, tóxica ou nociva",
                        "Inalação de substância cáustica, tóxica ou nociva",
                    ),
                    ("Ingestão de substância cáustica", "Ingestão de substância cáustica"),
                    ("Absorção de substância cáustica", "Absorção de substância cáustica"),
                    ("Inalação, ingestão ou absorção, NIC", "Inalação, ingestão ou absorção, NIC"),
                    ("Imersão", "Imersão"),
                    ("Radiação não ionizante, exposição à", "Radiação não ionizante, exposição à"),
                    ("Radiação ionizante, exposição à", "Radiação ionizante, exposição à"),
                    ("Ruído, exposição ao", "Ruído, exposição ao"),
                    ("Vibração, exposição à", "Vibração, exposição à"),
                    ("Pressão ambiente, exposição à", "Pressão ambiente, exposição à"),
                    ("Exposição à pressão ambiente elevada", "Exposição à pressão ambiente elevada"),
                    ("Exposição à pressão ambiente baixa", "Exposição à pressão ambiente baixa"),
                    (
                        "Poluição da água, ação da (exposição à poluição da água)",
                        "Poluição da água, ação da (exposição à poluição da água)",
                    ),
                    (
                        "Poluição do ar, ação da (exposição à poluição do ar)",
                        "Poluição do ar, ação da (exposição à poluição do ar)",
                    ),
                    (
                        "Poluição do solo, ação da (exposição à poluição do solo)",
                        "Poluição do solo, ação da (exposição à poluição do solo)",
                    ),
                    (
                        "Poluição, NIC, exposição à (exposição à poluição, NIC)",
                        "Poluição, NIC, exposição à (exposição à poluição, NIC)",
                    ),
                    (
                        "Ataque de ser vivo por mordedura, picada, chifrada, coice, etc.",
                        "Ataque de ser vivo por mordedura, picada, chifrada, coice, etc.",
                    ),
                    ("Ataque de ser vivo com peçonha", "Ataque de ser vivo com peçonha"),
                    (
                        "Ataque de ser vivo com transmissão de doença",
                        "Ataque de ser vivo com transmissão de doença",
                    ),
                    ("Ataque de ser vivo, NIC", "Ataque de ser vivo, NIC"),
                    ("Tipo, NIC", "Tipo, NIC"),
                    ("Tipo inexistente", "Tipo inexistente"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]

