# Generated by Django 4.2.27 on 2026-01-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_agentes_causadores(apps, schema_editor):
    AgenteCausador = apps.get_model("acidentes", "AgenteCausador")
    Company = apps.get_model("tenants", "Company")
    schema_name = schema_editor.connection.schema_name
    tenant = Company.objects.filter(schema_name=schema_name).first()
    if not tenant:
        return
    if AgenteCausador.objects.filter(company=tenant).exists():
        return

    base = [
        ("Rua e estrada", "superficie utilizada para sustentar pessoas"),
        ("Calcada ou caminho para pedestre", "superficie utilizada para sustentar pessoas"),
        ("Piso de edificio", "superficie utilizada para sustentar pessoas"),
        ("Escada permanente cujos degraus permitem apoio integral do pe, degrau", "superficie utilizada para sustentar pessoas"),
        ("Rampa", "superficie utilizada para sustentar pessoas"),
        ("Passarela ou plataforma permanentes", "superficie utilizada para sustentar pessoas"),
        ("Piso de mina", "superficie utilizada para sustentar pessoas"),
        ("Chao", "superficie utilizada para sustentar pessoas"),
        ("Piso de andaime e plataforma desmontavel", "superficie utilizada para sustentar pessoas"),
        ("Piso de veiculo", "superficie utilizada para sustentar pessoas"),
        ("Telhado", ""),
        ("Superficie de sustentacao, NIC", "superficie utilizada para sustentar pessoas"),
        ("Escada movel ou fixada, NIC", ""),
        ("Edificio", "edificio ou estrutura"),
        ("Deposito fixo (tanque, silo, paiol, etc.)", "edificio ou estrutura"),
        ("Area ou ambiente de trabalho", "inclui fenomeno atmosferico/meteoro e radiacao solar"),
        ("Agente do acidente, NIC", ""),
        ("Agente do acidente inexistente", ""),
        ("Energia", ""),
        ("Pressao ambiente alta", "trabalho em caixao pneumatico, mergulho"),
        ("Pressao ambiente baixa", "ar rarefeito"),
        ("Ruido", ""),
        ("Fogo, chama, material incandescente ou quente, fumaca", ""),
        ("Temperatura ambiente", "nao inclui a de objeto ou substancia quente"),
        ("Aerodispersoides", ""),
        ("Neblina", ""),
        ("Gas e vapor", ""),
    ]

    AgenteCausador.objects.bulk_create(
        [
            AgenteCausador(company=tenant, nome=nome, descricao=descricao, ativo=True)
            for nome, descricao in base
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0006_acidentetrabalho_situacao_geradora"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgenteCausador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "unique_together": {("company", "nome")},
            },
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="agente_causador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acidentes",
                to="acidentes.agentecausador",
            ),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="observacao",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(seed_agentes_causadores, migrations.RunPython.noop),
    ]

