# Generated by Django 4.2.27 on 2026-01-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_partes_atingidas(apps, schema_editor):
    ParteAtingida = apps.get_model("acidentes", "ParteAtingida")
    Company = apps.get_model("tenants", "Company")
    schema_name = schema_editor.connection.schema_name
    tenant = Company.objects.filter(schema_name=schema_name).first()
    if not tenant:
        return
    if ParteAtingida.objects.filter(company=tenant).exists():
        return

    base = [
        ("Crânio", "inclusive encéfalo"),
        ("Ouvido", "externo, médio, interno, audição e equilíbrio"),
        ("Olho", "inclusive nervo ótico e visão"),
        ("Nariz", "inclusive fossas nasais, seios da face e olfato"),
        ("Boca", "inclusive lábios, dentes, língua, garganta e paladar"),
        ("Mandíbula", "inclusive queixo"),
        ("Face, partes múltiplas", "qualquer combinação das partes acima"),
        ("Cabeça, partes múltiplas", "qualquer combinação das partes acima"),
        ("Cabeça, NIC", ""),
        ("Braço", "entre o punho e o ombro"),
        ("Braço", "acima do cotovelo"),
        ("Pescoço", ""),
        ("Cotovelo", ""),
        ("Antebraço", "entre o punho e o cotovelo"),
        ("Punho", ""),
        ("Mão", "exceto punho ou dedos"),
        ("Dedo", ""),
        ("Membros superiores, partes múltiplas", "qualquer combinação das partes acima"),
        ("Membros superiores, NIC", ""),
        ("Ombro", ""),
        ("Tórax", "inclusive órgãos internos"),
        ("Dorso", "inclusive músculos dorsais, coluna e medula espinhal"),
        ("Abdome", "inclusive órgãos internos"),
        ("Quadris", "inclusive pélvis, órgãos pélvicos e nádegas"),
        ("Tronco, partes múltiplas", "qualquer combinação das partes acima"),
        ("Tronco, NIC", ""),
        ("Perna", "entre o tornozelo e a pélvis"),
        ("Coxa", ""),
        ("Joelho", ""),
        ("Perna", "do tornozelo, exclusive, ao joelho, exclusive"),
        ("Articulação do tornozelo", ""),
        ("Pé", "exceto artelhos"),
        ("Artelho", ""),
        ("Membros inferiores, partes múltiplas", "qualquer combinação das partes acima"),
        ("Membros inferiores, NIC", ""),
        (
            "Partes múltiplas.",
            "aplica-se quando mais de uma parte importante do corpo for afetada, como, por exemplo, um braço e uma perna",
        ),
        (
            "Sistemas e aparelhos",
            "aplica-se quando o funcionamento de todo um sistema ou aparelho do corpo humano for afetado, sem lesão específica de qualquer outra parte, como no caso do envenenamento, ação corrosiva que afete órgãos internos, lesão dos centros nervosos, etc.; não se aplica quando a lesão sistêmica for provocada por lesão externa, como lesão dorsal que afete nervos da medula espinhal",
        ),
        ("Aparelho circulatório", ""),
        ("Aparelho respiratório", ""),
        ("Sistema nervoso", ""),
        ("Aparelho digestivo", ""),
        ("Aparelho gênito-urinário", ""),
        ("Sistema musculoesquelético", ""),
        ("Sistemas e aparelhos, NIC", ""),
        ("Localização da lesão, NIC", ""),
    ]

    created = []
    for nome, descricao in base:
        if not nome:
            continue
        obj, created_flag = ParteAtingida.objects.get_or_create(
            company=tenant,
            nome=nome,
            defaults={"descricao": descricao or "", "ativo": True},
        )
        if not created_flag and descricao and not obj.descricao:
            obj.descricao = descricao
            created.append(obj)
    if created:
        ParteAtingida.objects.bulk_update(created, ["descricao"])


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0007_agente_causador_e_observacao"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParteAtingida",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "unique_together": {("company", "nome")},
            },
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="parte_atingida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acidentes",
                to="acidentes.parteatingida",
            ),
        ),
        migrations.RunPython(seed_partes_atingidas, migrations.RunPython.noop),
    ]
