# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0008_parte_atingida"),
    ]

    operations = [
        migrations.AddField(
            model_name="acidentetrabalho",
            name="lateralidade",
            field=models.CharField(
                choices=[
                    ("nao_aplicavel", "Nao aplicavel"),
                    ("esquerda", "Esquerda"),
                    ("direita", "Direita"),
                    ("ambas", "Ambas"),
                ],
                default="nao_aplicavel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="severidade_potencial",
            field=models.CharField(
                choices=[
                    ("nao_aplicavel", "Nao aplicavel"),
                    ("leve", "Leve"),
                    ("moderada", "Moderada"),
                    ("critica", "Critica"),
                ],
                default="nao_aplicavel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="severidade_real",
            field=models.CharField(
                choices=[
                    ("nao_aplicavel", "Nao aplicavel"),
                    ("leve", "Leve"),
                    ("moderada", "Moderada"),
                    ("critica", "Critica"),
                ],
                default="nao_aplicavel",
                max_length=20,
            ),
        ),
    ]

