# Generated by Django 4.2.27 on 2026-01-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0009_lateralidade_e_severidades"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmitenteAtestado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=200)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "unique_together": {("company", "nome")},
            },
        ),
        migrations.CreateModel(
            name="NaturezaLesao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=200)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "unique_together": {("company", "nome")},
            },
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="codigo_cid10",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="codigo_cnes",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="data_atendimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="diagnostico_provavel",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="duracao_tratamento_dias",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="existe_atestado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="houve_internacao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="indicado_afastamento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="observacao_atestado",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="emitente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acidentes",
                to="acidentes.emitenteatestado",
            ),
        ),
        migrations.AddField(
            model_name="acidentetrabalho",
            name="natureza_lesao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acidentes",
                to="acidentes.naturezalesao",
            ),
        ),
    ]

