# Generated by Django 4.2.27 on 2026-01-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidentes', '0010_atestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='bairro',
            field=models.CharField(max_length=90, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='cidade',
            field=models.CharField(max_length=120, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='estado',
            field=models.CharField(choices=[('', 'Selecione'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhao'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'Sao Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='tipo_local',
            field=models.CharField(choices=[('', 'Selecione'), ('estabelecimento_brasil', 'Estab. do empregador Brasil'), ('estabelecimento_exterior', 'Estab. do empregador Exterior'), ('estabelecimento_terceiros', 'Estab. de terceiros'), ('via_publica', 'Via pública'), ('area_rural', 'Área rural'), ('embarcacao', 'Embarcação'), ('outros', 'Outros')], max_length=40),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='tipo_logradouro',
            field=models.CharField(choices=[('', 'Selecione'), ('rua', 'Rua'), ('avenida', 'Avenida'), ('estrada', 'Estrada'), ('praca', 'Praca'), ('area', 'Area'), ('acesso', 'Acesso'), ('alameda', 'Alameda'), ('bairro', 'Bairro'), ('beco', 'Beco'), ('boulevard', 'Boulevard'), ('caminho', 'Caminho'), ('chacara', 'Chacara'), ('conjunto', 'Conjunto'), ('condominio', 'Condominio'), ('distrito', 'Distrito'), ('fazenda', 'Fazenda'), ('jardim', 'Jardim'), ('loteamento', 'Loteamento'), ('parque', 'Parque'), ('rodovia', 'Rodovia'), ('rua_particular', 'Rua Particular'), ('servidao', 'Servidao'), ('sitio', 'Sitio'), ('travessa', 'Travessa'), ('via', 'Via'), ('vila', 'Vila'), ('outros', 'Outros')], max_length=40, verbose_name='Tipo do Logradouro'),
        ),
    ]
