# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations


def seed_natureza_lesao(apps, schema_editor):
    NaturezaLesao = apps.get_model("acidentes", "NaturezaLesao")
    Company = apps.get_model("tenants", "Company")
    schema_name = schema_editor.connection.schema_name
    tenant = Company.objects.filter(schema_name=schema_name).first()
    if not tenant:
        return

    itens = [
        "Lesão imediata",
        "Escoriação, abrasão (ferimento superficial)",
        "Corte, laceração, ferida contusa, punctura (ferida aberta)",
        "Contusão, esmagamento (superfície cutânea intacta)",
        "Distensão, torção",
        "Inflamação de articulação, tendão ou músculo",
        "Luxação",
        "Fratura",
        "Queimadura ou escaldadura - efeito de temperatura elevada ou efeito do contato com substância quente",
        "Queimadura química",
        "Efeito de radiação (imediato)",
        "Congelamento, geladura e outros efeitos da exposição à baixa temperatura",
        "Asfixia, estrangulamento, afogamento",
        "Intermação, insolação, cãibra, exaustão e outros efeitos da temperatura ambiente elevada",
        "Choque elétrico e eletroplessão (eletrocussão)",
        "Hérnia de qualquer natureza, ruptura",
        "Amputação ou enucleação",
        "Perda ou diminuição de sentido",
        "Concussão cerebral",
        "Lesão imediata, NIC",
        "Doença contagiosa ou infecciosa (tuberculose, brucelose, etc.)",
        "Pneumoconiose (silicose, asbestose, etc.)",
        "Dermatose (erupção, inflamação da pele, inclusive furúnculo, etc.)",
        "Envenenamento sistêmico",
        "Perda ou diminuição mediatas de sentido",
        "Efeito de radiação (mediato)",
        "Doença, NIC",
        "Lesões múltiplas",
        "Outras lesões, NIC",
    ]

    for nome in itens:
        NaturezaLesao.objects.get_or_create(company=tenant, nome=nome, defaults={"ativo": True})


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0010_atestado"),
    ]

    operations = [
        migrations.RunPython(seed_natureza_lesao, migrations.RunPython.noop),
    ]

