# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acidentes", "0011_alter_acidentetrabalho_bairro_and_more"),
        ("acidentes", "0011_seed_natureza_lesao"),
    ]

    operations = []

