# Generated by Django 4.2.27 on 2026-01-21 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_company_estoque_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acidentes', '0013_analise_fatos_anexos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidenteanexo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company'),
        ),
        migrations.AlterField(
            model_name='acidenteanexo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acidenteanexo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acidentefato',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company'),
        ),
        migrations.AlterField(
            model_name='acidentefato',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acidentefato',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='bairro',
            field=models.CharField(blank=True, max_length=90, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
    ]
