# Generated by Django 4.2.27 on 2026-01-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidentes', '0014_alter_acidenteanexo_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acidentetrabalho',
            name='caso_encerrado',
            field=models.BooleanField(default=False, verbose_name='Caso encerrado'),
        ),
    ]
