from django.urls import path

from . import views

app_name = "produtos"

urlpatterns = [
    path("produtos/", views.ProdutoListView.as_view(), name="list"),
    path("produtos/novo/", views.ProdutoCreateView.as_view(), name="create"),
    path("produtos/<int:pk>/editar/", views.ProdutoUpdateView.as_view(), name="update"),
    path("produtos/<int:pk>/toggle/", views.ProdutoToggleActiveView.as_view(), name="toggle_active"),
    path("produtos/<int:pk>/historico/", views.ProdutoHistoricoListView.as_view(), name="historico"),
    path("produtos/ca/", views.CaImportView.as_view(), name="ca_import"),
    path("produtos/ca/api/", views.CaImportApiView.as_view(), name="ca_import_api"),
    path("produtos/ca/fornecedor/", views.CaImportFornecedorApiView.as_view(), name="ca_import_fornecedor"),
    path("produtos/tipos/", views.TipoProdutoListView.as_view(), name="tipos_list"),
    path("produtos/tipos/novo/", views.TipoProdutoCreateView.as_view(), name="tipos_create"),
    path("produtos/tipos/<int:pk>/editar/", views.TipoProdutoUpdateView.as_view(), name="tipos_update"),
    path("produtos/tipos/<int:pk>/toggle/", views.TipoProdutoToggleActiveView.as_view(), name="tipos_toggle"),
    path("produtos/tipos/<int:pk>/excluir/", views.TipoProdutoDeleteView.as_view(), name="tipos_delete"),
    path("produtos/familias/", views.FamiliaProdutoListView.as_view(), name="familias_list"),
    path("produtos/familias/novo/", views.FamiliaProdutoCreateView.as_view(), name="familias_create"),
    path("produtos/familias/<int:pk>/editar/", views.FamiliaProdutoUpdateView.as_view(), name="familias_update"),
    path("produtos/familias/<int:pk>/toggle/", views.FamiliaProdutoToggleActiveView.as_view(), name="familias_toggle"),
    path("produtos/familias/<int:pk>/excluir/", views.FamiliaProdutoDeleteView.as_view(), name="familias_delete"),
    path("produtos/familias/<int:pk>/uso/", views.FamiliaProdutoUsoView.as_view(), name="familias_uso"),
    path("produtos/subfamilias/", views.SubfamiliaProdutoListView.as_view(), name="subfamilias_list"),
    path("produtos/subfamilias/novo/", views.SubfamiliaProdutoCreateView.as_view(), name="subfamilias_create"),
    path("produtos/subfamilias/<int:pk>/editar/", views.SubfamiliaProdutoUpdateView.as_view(), name="subfamilias_update"),
    path("produtos/subfamilias/<int:pk>/toggle/", views.SubfamiliaProdutoToggleActiveView.as_view(), name="subfamilias_toggle"),
    path("produtos/subfamilias/<int:pk>/excluir/", views.SubfamiliaProdutoDeleteView.as_view(), name="subfamilias_delete"),
    path("produtos/subfamilias/<int:pk>/uso/", views.SubfamiliaProdutoUsoView.as_view(), name="subfamilias_uso"),
    path("produtos/locais_retirada/", views.LocalRetiradaListView.as_view(), name="locais_retirada_list"),
    path("produtos/locais_retirada/novo/", views.LocalRetiradaCreateView.as_view(), name="locais_retirada_create"),
    path("produtos/locais_retirada/<int:pk>/editar/", views.LocalRetiradaUpdateView.as_view(), name="locais_retirada_update"),
    path("produtos/locais_retirada/<int:pk>/toggle/", views.LocalRetiradaToggleActiveView.as_view(), name="locais_retirada_toggle"),
    path("produtos/locais_retirada/<int:pk>/excluir/", views.LocalRetiradaDeleteView.as_view(), name="locais_retirada_delete"),
    path("produtos/periodicidades/", views.PeriodicidadeListView.as_view(), name="periodicidades_list"),
    path("produtos/periodicidades/novo/", views.PeriodicidadeCreateView.as_view(), name="periodicidades_create"),
    path("produtos/periodicidades/<int:pk>/editar/", views.PeriodicidadeUpdateView.as_view(), name="periodicidades_update"),
    path("produtos/periodicidades/<int:pk>/toggle/", views.PeriodicidadeToggleActiveView.as_view(), name="periodicidades_toggle"),
    path("produtos/periodicidades/<int:pk>/excluir/", views.PeriodicidadeDeleteView.as_view(), name="periodicidades_delete"),
    path("produtos/localizacoes/", views.LocalizacaoProdutoListView.as_view(), name="localizacoes_list"),
    path("produtos/localizacoes/novo/", views.LocalizacaoProdutoCreateView.as_view(), name="localizacoes_create"),
    path("produtos/localizacoes/<int:pk>/editar/", views.LocalizacaoProdutoUpdateView.as_view(), name="localizacoes_update"),
    path("produtos/localizacoes/<int:pk>/toggle/", views.LocalizacaoProdutoToggleActiveView.as_view(), name="localizacoes_toggle"),
    path("produtos/localizacoes/<int:pk>/excluir/", views.LocalizacaoProdutoDeleteView.as_view(), name="localizacoes_delete"),
]
