# Generated by Django 4.2.27 on 2025-12-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_funcionario', '0001_initial'),
        ('funcionarios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipos_funcionario.tipofuncionario'),
        ),
    ]
