# Generated by Django 4.2.27 on 2025-12-31 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerenciados', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ghe',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados', to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='turno',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
