# Generated by Django 4.2.27 on 2025-12-31 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('funcionarios', '0005_afastamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamento',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company'),
        ),
    ]
