# Generated by Django 4.2.27 on 2025-12-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('funcionarios', '0006_alter_afastamento_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto')], default='baixo', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='funcionarios.funcionario')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
