# Generated by Django 4.2.27 on 2025-12-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_afastamento_created_by_afastamento_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risco',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='riscos',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='funcionarios.risco'),
        ),
    ]
