# Generated by Django 4.2.27 on 2025-12-31 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_funcionario_refs(apps, schema_editor):
    Funcionario = apps.get_model('funcionarios', 'Funcionario')
    Turno = apps.get_model('funcionarios', 'Turno')
    GHE = apps.get_model('funcionarios', 'GHE')
    CentroCusto = apps.get_model('funcionarios', 'CentroCusto')

    for funcionario in Funcionario.objects.all().iterator():
        updates = {}
        if getattr(funcionario, 'turno', None):
            nome = str(funcionario.turno).strip()
            if nome:
                turno_obj, _ = Turno.objects.get_or_create(
                    company_id=funcionario.company_id,
                    nome=nome,
                )
                updates['turno_fk_id'] = turno_obj.id
        if getattr(funcionario, 'ghe', None):
            nome = str(funcionario.ghe).strip()
            if nome:
                ghe_obj, _ = GHE.objects.get_or_create(
                    company_id=funcionario.company_id,
                    nome=nome,
                )
                updates['ghe_fk_id'] = ghe_obj.id
        if getattr(funcionario, 'centro_custo', None):
            nome = str(funcionario.centro_custo).strip()
            if nome:
                cc_obj, _ = CentroCusto.objects.get_or_create(
                    company_id=funcionario.company_id,
                    nome=nome,
                )
                updates['centro_custo_fk_id'] = cc_obj.id
        if updates:
            Funcionario.objects.filter(pk=funcionario.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('funcionarios', '0012_funcionariohistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='turno_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.turno'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='centro_custo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.centrocusto'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ghe_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.ghe'),
        ),
        migrations.RunPython(migrate_funcionario_refs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='funcionario',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='ghe',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='turno_fk',
            new_name='turno',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='centro_custo_fk',
            new_name='centro_custo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='ghe_fk',
            new_name='ghe',
        ),
    ]
