# Generated by Django 4.2.27 on 2025-12-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_turno_ghe_centrocusto_alter_funcionario_centro_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='afastado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='categoria_cnh',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fim_ferias',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='identificador',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='inicio_ferias',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='temporario',
            field=models.BooleanField(default=False),
        ),
    ]
