# Generated by Django 4.2.27 on 2026-01-01 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_ghe_nome_to_descricao(apps, schema_editor):
    GHE = apps.get_model("funcionarios", "GHE")
    for ghe in GHE.objects.all():
        if getattr(ghe, "descricao", ""):
            continue
        nome = getattr(ghe, "nome", "") or ""
        if nome:
            ghe.descricao = nome
            ghe.save(update_fields=["descricao"])


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0015_centrocusto_ativo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ghe",
            name="codigo",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="ghe",
            name="descricao",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="ghe",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ghes_responsaveis",
                to="funcionarios.funcionario",
            ),
        ),
        migrations.AddField(
            model_name="ghe",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(copy_ghe_nome_to_descricao, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="ghe",
            name="nome",
        ),
        migrations.AlterModelOptions(
            name="ghe",
            options={"ordering": ["codigo", "descricao"]},
        ),
    ]
