# Generated by Django 4.2.27 on 2026-01-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0024_advertencia_descricao_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='validacao_recebimento',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('senha', 'Senha'), ('assinatura', 'Assinatura')], default='nenhum', max_length=10),
        ),
    ]
