# Generated by Django 4.2.27 on 2026-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0005_deposito_bloquear_movimento_negativo'),
        ('produtos', '0039_migrar_grade_texto_para_model'),
        ('estoque', '0003_actionlog_created_by_actionlog_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estoque',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('produto', 'grade', 'deposito')},
        ),
    ]
