# Generated by Django 4.2.27 on 2025-12-31 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0004_produto_created_by_produto_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_externo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='produto',
            name='controle_epi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='dias_entrega',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_ideal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='imposto_ipi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='imposto_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='imposto_st',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='monitora_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='obrigar_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('dias', 'Dias'), ('semanas', 'Semanas'), ('meses', 'Meses'), ('anos', 'Anos'), ('quinzena', 'Quinzena'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre')], max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='troca_funcionario',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MarcaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.marcaproduto'),
        ),
    ]
