# Generated by Django 4.2.27 on 2025-12-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_tipoproduto_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtofornecedor',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtofornecedor',
            name='fator_compra',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
    ]
