# Generated by Codex on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0008_produtofornecedor_data_vencimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtofornecedor",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RemoveField(
            model_name="produto",
            name="codigo_barras",
        ),
    ]
