# Generated by Codex on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0009_produtofornecedor_codigo_barras_and_remove_produto_codigo_barras"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtofornecedor",
            name="ca",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="produtofornecedor",
            name="codigo_fornecedor",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
