# Generated by Django 4.2.27 on 2026-01-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0012_subfamilia_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subfamiliaproduto",
            name="familia",
        ),
    ]
