# Generated by Django 4.2.27 on 2025-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0023_tipoproduto_ativo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaEPI",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registro_ca", models.CharField(max_length=50)),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("situacao", models.CharField(blank=True, max_length=60)),
                ("nr_processo", models.CharField(blank=True, max_length=60)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("razao_social", models.CharField(blank=True, max_length=255)),
                ("natureza", models.CharField(blank=True, max_length=120)),
                ("nome_equipamento", models.CharField(blank=True, max_length=255)),
                ("descricao_equipamento", models.TextField(blank=True)),
                ("marca_ca", models.CharField(blank=True, max_length=120)),
                ("referencia", models.CharField(blank=True, max_length=120)),
                ("cor", models.CharField(blank=True, max_length=60)),
                ("aprovado_para_laudo", models.CharField(blank=True, max_length=60)),
                ("restricao_laudo", models.TextField(blank=True)),
                ("observacao_analise_laudo", models.TextField(blank=True)),
                ("cnpj_laboratorio", models.CharField(blank=True, max_length=20)),
                ("razao_social_laboratorio", models.CharField(blank=True, max_length=255)),
                ("nr_laudo", models.CharField(blank=True, max_length=60)),
                ("norma", models.CharField(blank=True, max_length=120)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caepi_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caepi_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_validade", "registro_ca"],
            },
        ),
    ]
