# Generated by Django 4.2.27 on 2025-01-01 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0024_caepi"),
    ]

    operations = [
        migrations.AddField(
            model_name="caepi",
            name="ultima_atualizacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
