# Generated by Django 4.2.27 on 2025-01-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0025_caepi_ultima_atualizacao"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaEPI",
        ),
    ]
