# Generated by Django 4.2.27 on 2026-01-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0027_alter_produto_estoque_ideal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_ideal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imposto_ipi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imposto_st',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
