# Generated by Django 4.2.27 on 2026-01-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0028_alter_produto_estoque_ideal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imposto_outros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
