# Generated by Django 4.2.27 on 2026-01-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0029_alter_produto_imposto_outros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtofornecedor',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='codigo_fornecedor',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
