# Generated by Django 4.2.27 on 2026-01-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0030_alter_produtofornecedor_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtofornecedor',
            name='fator_compra',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=12, null=True),
        ),
    ]
