# Generated by Django 4.2.27 on 2026-01-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0031_alter_produtofornecedor_fator_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtofornecedor',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
