# Generated by Django 4.2.27 on 2026-01-16 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_company_estoque_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0032_alter_produtofornecedor_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='produtofornecedor',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='produtofornecedor',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='produto',
            name='ca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_vencimento_ca',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('ie', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('site', models.URLField(blank=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.fabricante'),
        ),
        migrations.AddIndex(
            model_name='fabricante',
            index=models.Index(fields=['nome'], name='produtos_fa_nome_9e0906_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricante',
            index=models.Index(fields=['cnpj'], name='produtos_fa_cnpj_37d31d_idx'),
        ),
    ]
