# Generated by GPT-5.2 on 2026-01-17

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0033_remove_produto_fornecedor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="sku",
            new_name="codigo",
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                fields=("company", "codigo"),
                condition=~Q(codigo=""),
                name="produtos_produto_company_codigo_uniq",
            ),
        ),
    ]

