# Generated by Django 4.2.27 on 2026-01-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0034_produto_codigo_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo_externo',
        ),
    ]
