# Generated by GPT-5.2 on 2026-01-22

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower


def dedupe_codigo_ca(apps, schema_editor):
    Produto = apps.get_model("produtos", "Produto")

    # CA duplicado (case-insensitive) dentro da mesma empresa:
    # mantém o primeiro registro e limpa o CA dos demais (também desliga controle_epi para evitar inconsistência).
    seen_ca = {}
    dup_ca_ids = []
    for pk, company_id, ca, controle_epi in Produto.objects.exclude(ca="").values_list(
        "pk",
        "company_id",
        "ca",
        "controle_epi",
    ).iterator():
        key = (company_id, (ca or "").strip().lower())
        if not key[1]:
            continue
        if key in seen_ca:
            dup_ca_ids.append(pk)
        else:
            seen_ca[key] = pk

    if dup_ca_ids:
        # Limpa campos dependentes do CA para não bloquear edições futuras.
        Produto.objects.filter(pk__in=dup_ca_ids).update(
            ca="",
            controle_epi=False,
            data_vencimento_ca=None,
            fabricante=None,
        )

    # Codigo duplicado (case-insensitive) dentro da mesma empresa:
    # mantém o primeiro e ajusta os demais com sufixo do PK (evita quebrar NOT NULL/uso do codigo).
    seen_codigo = {}
    updates = []
    for pk, company_id, codigo in Produto.objects.exclude(codigo="").values_list("pk", "company_id", "codigo").iterator():
        norm = (codigo or "").strip().lower()
        if not norm:
            continue
        key = (company_id, norm)
        if key not in seen_codigo:
            seen_codigo[key] = pk
            continue
        base = (codigo or "").strip()
        suffix = f"-{pk}"
        new_codigo = (base[: (80 - len(suffix))] + suffix) if len(base) + len(suffix) > 80 else (base + suffix)
        updates.append((pk, new_codigo))

    if updates:
        for pk, new_codigo in updates:
            Produto.objects.filter(pk=pk).update(codigo=new_codigo)


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0035_remove_produto_codigo_externo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="produto",
            name="produtos_produto_company_codigo_uniq",
        ),
        migrations.RunPython(dedupe_codigo_ca, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                Lower("codigo"),
                "company",
                condition=~Q(codigo=""),
                name="produtos_produto_company_codigo_ci_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                Lower("ca"),
                "company",
                condition=~Q(ca=""),
                name="produtos_produto_company_ca_ci_uniq",
            ),
        ),
    ]
