# Generated by Django 4.2.27 on 2026-01-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0036_produto_ca_codigo_unique_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='grade',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
