# Generated by OpenAI Codex on 2026-01-24

import re

from django.db import migrations


def forwards(apps, schema_editor):
    Produto = apps.get_model("produtos", "Produto")
    GradeProduto = apps.get_model("produtos", "GradeProduto")
    ProdutoGrade = apps.get_model("produtos", "ProdutoGrade")

    splitter = re.compile(r"[,\n;/]+")
    cache = {}

    qs = Produto.objects.all()
    for produto in qs.iterator():
        raw = (getattr(produto, "grade", "") or "").strip()
        if not raw:
            continue
        parts = splitter.split(raw)
        for part in parts:
            nome = (part or "").strip()
            if not nome:
                continue
            key = (produto.company_id, nome.lower())
            grade_obj = cache.get(key)
            if grade_obj is None:
                grade_obj = GradeProduto.objects.filter(company_id=produto.company_id, nome__iexact=nome).first()
                if grade_obj is None:
                    grade_obj = GradeProduto.objects.create(company_id=produto.company_id, nome=nome, ativo=True)
                cache[key] = grade_obj
            ProdutoGrade.objects.get_or_create(
                company_id=produto.company_id,
                produto_id=produto.pk,
                grade_id=grade_obj.pk,
            )


def backwards(apps, schema_editor):
    # Mantem dados existentes; nao desfaz migracao automaticamente.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0038_gradeproduto_produtograde_produto_grades_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

