# Generated by Django 4.2.27 on 2025-12-31 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='deposito',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
