# Generated by Django 4.2.27 on 2026-01-25 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0025_alter_funcionario_validacao_recebimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_company_estoque_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CipaEleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('mandato_inicio', models.DateField(blank=True, null=True)),
                ('mandato_fim', models.DateField(blank=True, null=True)),
                ('inscricoes_inicio', models.DateTimeField(blank=True, null=True)),
                ('inscricoes_fim', models.DateTimeField(blank=True, null=True)),
                ('votacao_inicio', models.DateTimeField(blank=True, null=True)),
                ('votacao_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('inscricoes', 'Inscricoes'), ('votacao', 'Votacao'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cipa_eleicoes', to='funcionarios.planta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CipaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('indeferido', 'Indeferido')], default='pendente', max_length=20)),
                ('motivo_indeferimento', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='cipa.cipaeleicao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cipa_candidaturas', to='funcionarios.funcionario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero', 'id'],
                'unique_together': {('company', 'eleicao', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='CipaVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('candidato', 'Candidato'), ('branco', 'Branco'), ('nulo', 'Nulo')], default='candidato', max_length=20)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos', to='cipa.cipacandidato')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='cipa.cipaeleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cipa_votos', to='funcionarios.funcionario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('company', 'eleicao', 'eleitor')},
            },
        ),
    ]
