# Generated by Django 4.2.27 on 2026-01-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipaeleicao',
            name='escopo',
            field=models.CharField(choices=[('global', 'Global'), ('planta', 'Por planta')], default='planta', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cipaeleicao',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('escopo', 'global'), ('planta__isnull', True)), models.Q(('escopo', 'planta'), ('planta__isnull', False)), _connector='OR'), name='cipa_eleicao_scope_planta_consistency'),
        ),
    ]
