# Generated by Django 4.2.27 on 2026-01-25 23:08

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cipa', '0002_cipaeleicao_escopo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cipaeleicao',
            name='inscricoes_fim',
        ),
        migrations.RemoveField(
            model_name='cipaeleicao',
            name='inscricoes_inicio',
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='candidatura_publica_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='candidatura_publica_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='data_abertura_candidaturas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='data_comunicacao_sindicato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='data_divulgacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='data_divulgacao_candidatos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='data_eleicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='data_fim_ultimo_mandato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='data_inicio_processo_eleitoral',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='eleicao_extraordinaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='grau_risco',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='qt_colaboradores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='qt_efetivos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='qt_suplentes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='wizard_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
