# Generated by Django 4.2.27 on 2026-01-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipa', '0003_remove_cipaeleicao_inscricoes_fim_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cipaeleicao',
            name='cipa_eleicao_scope_planta_consistency',
        ),
        migrations.AddConstraint(
            model_name='cipaeleicao',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('planta__isnull', True), ('wizard_step', 1)), models.Q(('escopo', 'global'), ('planta__isnull', True)), models.Q(('escopo', 'planta'), ('planta__isnull', False)), _connector='OR'), name='cipa_eleicao_scope_planta_consistency'),
        ),
    ]
