# Generated by Django 4.2.27 on 2026-01-25 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cipa', '0004_remove_cipaeleicao_cipa_eleicao_scope_planta_consistency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipaeleicao',
            name='votacao_publica_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cipaeleicao',
            name='votacao_publica_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
