# Generated by Django 4.2.27 on 2026-01-26 12:45

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("cipa", "0005_cipaeleicao_votacao_publica_ativa_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cipaeleicao",
            constraint=models.UniqueConstraint(
                Lower("nome"),
                "company",
                name="cipa_eleicao_unique_company_nome_ci",
            ),
        ),
    ]
