# Generated by Codex on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setores", "0003_setor_created_by_setor_updated_by"),
        ("funcionarios", "0013_turno_ghe_centrocusto_alter_funcionario_centro_custo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setor",
            name="responsaveis",
            field=models.ManyToManyField(blank=True, related_name="setores_responsaveis", to="funcionarios.funcionario"),
        ),
    ]
