# Generated by Django 4.2.27 on 2026-01-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_entrega_entregue_em_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('entregue', 'Entregue'), ('cancelada', 'Cancelada'), ('aguardando', 'Aguardando entrega')], default='entregue', max_length=20),
        ),
    ]
