# Generated by Django 4.2.27 on 2026-01-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entregas", "0006_alter_entrega_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrega",
            name="assinatura",
            field=models.ImageField(blank=True, null=True, upload_to="entregas/assinaturas/"),
        ),
    ]
