# Generated by Django 4.2.27 on 2026-01-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entregas", "0007_entrega_assinatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrega",
            name="validacao_recebimento",
            field=models.CharField(
                choices=[("nenhum", "Nenhum"), ("senha", "Senha"), ("assinatura", "Assinatura")],
                default="nenhum",
                max_length=10,
            ),
        ),
    ]
