# Generated by Django 4.2.27 on 2026-01-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_entrega_items(apps, schema_editor):
    Entrega = apps.get_model("entregas", "Entrega")
    EntregaItem = apps.get_model("entregas", "EntregaItem")

    missing = Entrega.objects.filter(itens__isnull=True).only(
        "id",
        "company_id",
        "produto_id",
        "deposito_id",
        "quantidade",
        "ca",
        "observacao",
        "created_by_id",
        "updated_by_id",
    )
    batch = []
    for entrega in missing.iterator():
        if not entrega.produto_id or not entrega.deposito_id or entrega.quantidade is None:
            continue
        batch.append(
            EntregaItem(
                company_id=entrega.company_id,
                entrega_id=entrega.id,
                produto_id=entrega.produto_id,
                deposito_id=entrega.deposito_id,
                quantidade=entrega.quantidade,
                ca=entrega.ca or "",
                grade="",
                observacao=entrega.observacao or "",
                created_by_id=getattr(entrega, "created_by_id", None),
                updated_by_id=getattr(entrega, "updated_by_id", None),
            )
        )
        if len(batch) >= 1000:
            EntregaItem.objects.bulk_create(batch)
            batch = []
    if batch:
        EntregaItem.objects.bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ("entregas", "0009_entregaitem_grade"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Devolucao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("devolvida_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("observacao", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devolucoes",
                        to="entregas.entrega",
                    ),
                ),
            ],
            options={
                "ordering": ["-devolvida_em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DevolucaoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "condicao",
                    models.CharField(
                        choices=[
                            ("boa", "Boa"),
                            ("usada", "Usada"),
                            ("danificada", "Danificada"),
                            ("vencida", "Vencida"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "devolucao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="entregas.devolucao",
                    ),
                ),
                (
                    "entrega_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devolucoes_itens",
                        to="entregas.entregaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(backfill_entrega_items, migrations.RunPython.noop),
    ]

