# Generated by Django 4.2.27 on 2026-01-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entregas", "0011_devolucao_assinatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="devolucaoitem",
            name="volta_para_estoque",
            field=models.BooleanField(default=True),
        ),
    ]

